language: ruby
cache: bundler
os:
- linux
- osx
rvm:
- 2.5
- 2.4
- 2.3
- ruby-head
before_install:
- gem install bundler -v 2.0.1
- bundle update
- curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/travis-plantuml-install.sh | bash
matrix:
  allow_failures:
    - rvm: ruby-head
