== copyright-statement
=== {% if stage_int >= 40 %}DOCUMENT PROTÉGÉ PAR COPYRIGHT{%else%}{blank}{%endif%}

[[boilerplate-year]]
&#xa9; span:std_publisher:[{{ agency }}] span:std_docNumber[{{ docyear }}]

[[boilerplate-message]]
Droits de reproduction réservés. Sauf indication contraire, ou requise dans le cadre de sa mise en œuvre,
aucune partie de cette publication ne
peut être reproduite ni utilisée sous quelque forme que ce soit et par aucun procédé, électronique
ou mécanique, y compris la photocopie, l’affichage sur l’internet ou sur un Intranet, sans
autorisation écrite préalable. Les demandes d’autorisation peuvent être adressées à l’ISO à
l’adresse ci-après ou au comité membre de l’ISO dans le pays du demandeur.

[[boilerplate-address]]
[align="left"]
ISO copyright office +
CP 401 &#x2022; Ch. de Blandonnet 8 +
CH-1214 Vernier, Geneva +
Tél: +41 22 749 01 11 +
Email: copyright@iso.org +
Website: www.iso.org

[[boilerplate-place]]
Publié en Suisse

{% if unpublished %}
== license-statement
=== Avertissement

Ce document n'est pas une Norme internationale de l'ISO. Il est distribué pour examen et observations. Il est susceptible de modification sans préavis et ne peut être cité comme Norme internationale.

Les destinataires du présent projet sont invités à présenter, avec leurs observations, notification des droits de propriété dont ils auraient éventuellement connaissance et à fournir une documentation explicative.
{% endif %}
