== copyright-statement

{% if document_scheme == "1972" or document_scheme == "1987" %}

[[boilerplate-copyright-default]]
=== {blank}

[[boilerplate-year]]
&#xa9;&#xa0;&#xa0;&#xa0;span:std_publisher[*Международная Организация по Стандартизации*], span:date[*{{ docyear }}*]&#xa0;&#xa0;&#xa0;&#x25cf;

[[boilerplate-place]]
Издано в Швейцарии

{% elsif document_scheme == "1989" %}

[[boilerplate-copyright-default]]
=== {blank}

[[boilerplate-year]]
&#xa9; span:std_publisher[{{ agency }}&#xa0;]span:date[{{ docyear }}]

[[boilerplate-message]]
Охраняется авторским правом. Если это особо не указано, то никакая часть данной публикации не может быть воспроизведена и 
использована в любой форме или любыми средствами, электронными или механическими, включая фотокопирование и
микрофильмирование, без предварительного письменного разрешения издателя.

[[boilerplate-address]]
[align=left]
Международная Организация по Стандартизации +
Почтовый адрес: 56 &#x2022; CH-1211 Geneva 20 &#x2022; Switzerland +
Адрес в Интернете:&#xa0;central@iso.ch +
X.400&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;c=ch; a=400net; p=iso; o=isocs; s=central

[[boilerplate-place]]
Напечатано в Швейцарии

{% else %}

[[boilerplate-copyright-default]]
=== {% if stage_int >= 40 %}ДОКУМЕНТ, ОХРАНЯЕМЫЙ АВТОРСКИМ ПРАВОМ{% else %}{blank}{% endif %}

[[boilerplate-year]]
&#xa9; span:std_publisher[{{ agency }}&#xa0;]span:date[{{ docyear }}]

[[boilerplate-message]]
Все права защищены. Если иначе не определено или не требуется в контексте его реализации, никакая часть этой публикации не может быть воспроизведена или использована иначе в любой форме или каким-либо образом, электронным или механическим, включая фотокопирование, или публикацию в Интернете или интранете, без предварительного письменного разрешения. Разрешение может быть запрошено ISO по адресу, указанному ниже, или у органа — члена ISO страны запрашивающего.

[[boilerplate-address]]
[align="left"]
Бюро ISO по охране авторских прав +
CP 401 &#x2022; Ch. de Blandonnet 8 +
CH-1214 Vernier, Geneva +
Тел: +41 22 749 01 11 +
Электронная почта: copyright@iso.org +
Сайт: {% if document_scheme == "2024" %}https://www.iso.org/[www.iso.org]{% else %}www.iso.org{% endif %}

[[boilerplate-place]]
Издано в Швейцарии

{% if stage_int >= 20 and stage_int < 40 %}
== license-statement
=== Предупреждение для WD и CD

Этот документ не является международным стандартом ISO. Распространяется для ознакомления и комментариев. Оно может быть изменено без предварительного уведомления и не может упоминаться как международный стандарт.

Получателям этого проекта предлагается представить вместе со своими комментариями уведомление о любых соответствующих патентных правах, о которых им известно, и предоставить подтверждающую документацию.
{% endif %}
{% endif %}
