== copyright-statement
{% if document_scheme == "1951" %}

=== REPRODUCTION INTERDITE

[[boilerplate-message]]
Le droit de reproduction des Recommandations ISO et des Normes
ISO est la propriété des Comités Membres de l’ISO. En 
conséquence, dans chaque pays, la reproduction de ces documents ne
peut être autorisée que par l’organisation nationale de 
normalisation sation de ce pays, membre de I’ISO.

Seules les normes nationales sont valables dans leurs pays respectifs.

[[boilerplate-place]]
Imprimé en Suisse

Ce document est également édité en anglais et en russe. Il peut être obtenu auprès des organisations +
nationales de normalisation.

{% elsif document_scheme == "1972" or document_scheme == "1987" %}

=== {blank}

[[boilerplate-year]]
&#xa9;&#xa0;&#xa0;&#xa0;span:std_publisher[*Organisation Nationale de Normalisation*], span:date[*{{ docyear }}*]&#xa0;&#xa0;&#xa0;&#x25cf;

[[boilerplate-place]]
Publié en Suisse


{% elsif document_scheme == "1989" %}

=== {blank}

[[boilerplate-year]]
&#xa9; span:std_publisher[{{ agency }}&#xa0;]span:date[{{ docyear }}]

[[boilerplate-message]]
Droits de reproduction réservés. Sauf prescription différente, aucune partie de cette publication 
ne peut être reproduite ni utilisée sous quelque forme que ce soit et par aucun procédé, 
électronique ou mécanique, y compris la photocopie et les microfilms, sans l'accord écrit de l'éditeur. 

[[boilerplate-address]]
[align=left]
Organisation internationale de normalisation +
Case postale 56 &#x2022; CH-1211 Genève 20 &#x2022; Suisse +
Internet&#xa0;&#xa0;&#xa0;central@iso.ch +
X.400&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;&#xa0;c=ch; a=400net; p=iso; o=isocs; s=central 

[[boilerplate-place]]
Imprimé en Suisse


{% else %}
=== {% if stage_int >= 40 %}DOCUMENT PROTÉGÉ PAR COPYRIGHT{%else%}{blank}{%endif%}

[[boilerplate-year]]
&#xa9; span:std_publisher:[{{ agency }}&#xa0;]span:date[{{ docyear }}]

[[boilerplate-message]]
Droits de reproduction réservés. Sauf indication contraire, ou requise dans le cadre de sa mise en œuvre,
aucune partie de cette publication ne
peut être reproduite ni utilisée sous quelque forme que ce soit et par aucun procédé, électronique
ou mécanique, y compris la photocopie, l’affichage sur l’internet ou sur un Intranet, sans
autorisation écrite préalable. Les demandes d’autorisation peuvent être adressées à l’ISO à
l’adresse ci-après ou au comité membre de l’ISO dans le pays du demandeur.

[[boilerplate-address]]
[align="left"]
ISO copyright office +
CP 401 &#x2022; Ch. de Blandonnet 8 +
CH-1214 Vernier, Geneva +
Tél: +41 22 749 01 11 +
Email: copyright@iso.org +
Website: {% if document_scheme == "2024" %}https://www.iso.org/[www.iso.org]{% else %}www.iso.org{% endif %}

[[boilerplate-place]]
Publié en Suisse

{% if stage_int >= 20 and stage_int < 40 %}
== license-statement
=== Avertissement

Ce document n'est pas une Norme internationale de l'ISO. Il est distribué pour examen et observations. Il est susceptible de modification sans préavis et ne peut être cité comme Norme internationale.

Les destinataires du présent projet sont invités à présenter, avec leurs observations, notification des droits de propriété dont ils auraient éventuellement connaissance et à fournir une documentation explicative.
{% endif %}
{% endif %}
