== copyright-statement

{% if document_scheme == "1951" %}

=== COPYRIGHT RESERVED

[[boilerplate-message]]
The copyright of ISO Recommendations and ISO Standards
belongs to ISO Member Bodies. Reproduction of these 
documents, in any country, may be authorized therefore only
by the national standards organization of that country, being
a member of ISO.

For each individual country the only valid standard is the national standard of that country.

[[boilerplate-place]]
Printed in Switzerland

Also issued in French and Russian. Copies to be obtained through the national standards organizations.

{% elsif document_scheme == "1972" or document_scheme == "1987" %}

=== {blank}

[[boilerplate-year]]
&#xa9;&#xa0;&#xa0;&#xa0;span:std_publisher[*International Organization for Standardization*], span:std_docNumber[*{{ docyear }}*]&#xa0;&#xa0;&#xa0;&#x25cf;

[[boilerplate-place]]
Printed in Switzerland

{% else %}

=== {% if stage_int >= 40 %}COPYRIGHT PROTECTED DOCUMENT{% else %}{blank}{% endif %}

[[boilerplate-year]]
&#xa9; span:std_publisher[{{ agency }}&#xa0;]span:std_docNumber[{{ docyear }}]

[[boilerplate-message]]
All rights reserved. Unless otherwise specified, or required in the context of its implementation,
no part of this publication may be
reproduced or utilized otherwise in any form or by any means, electronic or
mechanical, including photocopying, or posting on the internet or an intranet,
without prior written permission. Permission can be requested from either ISO
at the address below or ISO's member body in the country of the requester.

[[boilerplate-address]]
[align=left]
ISO copyright office +
CP 401 &#x2022; Ch. de Blandonnet 8 +
CH-1214 Vernier, Geneva +
Phone: +41 22 749 01 11 +
Email: copyright@iso.org +
Website: www.iso.org

[[boilerplate-place]]
Published in Switzerland

{% if unpublished %}
== license-statement
=== Warning for WDs and CDs

This document is not an ISO International Standard. It is distributed for review and
comment. It is subject to change without notice and may not be referred to as
an International Standard.

Recipients
of this draft are invited to submit, with their comments, notification of any
relevant patent rights of which they are aware and to provide supporting
documentation.
{% endif %}
{% endif %}
