module Metanorma
  module Iso
    class Converter
      ISO_LOG_MESSAGES = {
        # rubocop:disable Naming/VariableNumber
        "ISO_1": { category: "Style",
                   error: "Style override set for ordered list",
                   severity: 2 },
        "ISO_2": { category: "Document Attributes",
                   error: "invalid technical committee type %s",
                   severity: 2 },
        "ISO_3": { category: "Document Attributes",
                   error: "invalid subcommittee type %s",
                   severity: 2 },
        "ISO_4": { category: "Style",
                   error: "term definition starts with article: %s",
                   severity: 2 },
        "ISO_5": { category: "Document Attributes",
                   error: "%s is not a recognised document type", severity: 2 },
        "ISO_6": { category: "Document Attributes",
                   error: "%s is not a recognised iteration", severity: 2 },
        "ISO_7": { category: "Style",
                   error: "%s is not permitted in a subfigure", severity: 2 },
        "ISO_8": { category: "Style",
                   error: "Reference does not have an associated footnote indicating unpublished status",
                   severity: 2 },
        "ISO_9": { category: "Document Attributes",
                   error: "Illegal document stage: %s.%s", severity: 2 },
        "ISO_10": { category: "Style", error: "No English Title Intro!",
                    severity: 2 },
        "ISO_11": { category: "Style", error: "No French Title Intro!",
                    severity: 2 },
        "ISO_12": { category: "Style", error: "No English Title!",
                    severity: 2 },
        "ISO_13": { category: "Style", error: "No French Title!", severity: 2 },
        "ISO_14": { category: "Style", error: "No English Title Part!",
                    severity: 2 },
        "ISO_15": { category: "Style", error: "No French Title Part!",
                    severity: 2 },
        "ISO_16": { category: "Style",
                    error: "Subpart defined on non-IEC document!",
                    severity: 2 },
        "ISO_17": { category: "Style",
                    error: "Main Title may name document type",
                    severity: 2 },
        "ISO_18": { category: "Style",
                    error: "Title Intro may name document type",
                    severity: 2 },
        "ISO_19": { category: "Style",
                    error: "%s: each first-level subclause must have a title",
                    severity: 2 },
        "ISO_20": { category: "Style",
                    error: "%s: all subclauses must have a title, or none",
                    severity: 2 },
        "ISO_21": { category: "Style", error: "%s %s has not been cross-referenced within document",
                    severity: 1 },
        "ISO_22": { category: "Style", error: "(formula) %s %s has not been cross-referenced within document",
                    severity: 2 },
        "ISO_23": { category: "Style", error: "foreword contains subclauses",
                    severity: 2 },
        "ISO_24": { category: "Style",
                    error: "normative references contains subclauses",
                    severity: 2 },
        "ISO_25": { category: "Style",
                    error: "Only one Symbols and Abbreviated Terms section in the standard",
                    severity: 2 },
        "ISO_26": { category: "Style",
                    error: "Symbols and Abbreviated Terms can only contain a definition list",
                    severity: 2 },
        "ISO_27": { category: "Style",
                    error: "In vocabulary documents, Symbols and Abbreviated Terms are only permitted in annexes",
                    severity: 2 },
        "ISO_28": { category: "Style", error: "(section sequencing) %s",
                    severity: 2 },
        "ISO_29": { category: "Style", error: "Scope clause missing",
                    severity: 2 },
        "ISO_30": { category: "Style", error: "Normative references missing",
                    severity: 2 },
        "ISO_31": { category: "Style", error: "Terms & definitions missing",
                    severity: 2 },
        "ISO_32": { category: "Style",
                    error: "Document must contain at least one clause",
                    severity: 2 },
        "ISO_33": { category: "Style",
                    error: "Document must contain clause after Terms and Definitions",
                    severity: 2 },
        "ISO_34": { category: "Style",
                    error: "Scope must not occur after Terms and Definitions",
                    severity: 2 },
        "ISO_35": { category: "Style",
                    error: "term definition ends with period: %s",
                    severity: 2 },
        "ISO_36": { category: "Style",
                    error: "Only annexes and references can follow clauses",
                    severity: 2 },
        "ISO_37": { category: "Style",
                    error: "Only annexes and references can follow terms and clauses",
                    severity: 2 },
        "ISO_38": { category: "Style",
                    error: "Document must include (references) Normative References",
                    severity: 2 },
        "ISO_39": { category: "Style",
                    error: "Scope contains subclauses: should be succinct",
                    severity: 2 },
        "ISO_40": { category: "Style",
                    error: "Final section must be (references) Bibliography",
                    severity: 2 },
        "ISO_41": { category: "Style",
                    error: "There are sections after the final Bibliography",
                    severity: 2 },
        "ISO_42": { category: "Style",
                    error: "non-ISO/IEC reference is allowed as normative only subject to the conditions in ISO/IEC DIR 2 10.2: %s",
                    severity: 2 },
        "ISO_43": { category: "Style", error: "subclause is only child",
                    severity: 2 },
        "ISO_44": { category: "Style",
                    error: "Single terms clause in vocabulary document should have normal Terms and definitions heading",
                    severity: 2 },
        "ISO_45": { category: "Style",
                    error: "Multiple terms clauses in vocabulary document should have 'Terms related to' heading",
                    severity: 2 },
        "ISO_46": { category: "Style",
                    error: "'see %s' is pointing to a normative section",
                    severity: 2 },
        "ISO_47": { category: "Bibliography",
                    error: "'%s is not pointing to a real reference",
                    severity: 2 },
        "ISO_48": { category: "Style",
                    error: "'see %s' is pointing to a normative reference",
                    severity: 2 },
        "ISO_49": { category: "Style",
                    error: "undated reference %s should not contain specific elements",
                    severity: 2 },
        "ISO_50": { category: "Style",
                    error: "only terms clauses can cross-reference terms clause (%s)",
                    severity: 2 },
        "ISO_51": { category: "Style",
                    error: "non-terms clauses cannot cross-reference terms clause (%s)",
                    severity: 2 },
      }.freeze
      # rubocop:enable Naming/VariableNumber

      def log_messages
        super.merge(ISO_LOG_MESSAGES)
      end
    end
  end
end
