= Quickstart Guide

TIP: This guide has been authored for ISO standards, but most of it applies to all Metanorma standards. We indicate where guidance differs for different standards classes. See link:https://www.metanorma.com/software/Metanorma_processor/[List of Metanorma processors].

This is a guide on how to get started using Metanorma to create documents aligned with different standards classes (such as ISO, GB, CSD, etc), in Microsoft Word and HTML formats. This guide is written to apply generically across the standards classes that can be expressed in Metanorma; guidance specific to a particular standards class is given as TIPs.

Metanorma takes text in the _Asciidoctor markup language_ as input (consult the https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual] on the basics of this markup language).
Metanorma makes some adjustments to the text format for its requirements;
these adjustments (which we refer to as _Metanorma Asciidoctor_, or AsciiISO) are documented in relevant sections of this documentation.
Metanorma uses Asciidoctor to generate _Metanorma XML_, as an intermediate, semantic representation of standards content.
Metanorma XML in turn is processed by the https://github.com/riboseinc/isodoc[isodoc] gem to generate output in Microsoft Word (`.doc`) and HTML (`.html`).


[[installation]]
== Installing on Linux and macOS

Install Metanorma-ISO gem and its dependencies:

[source,console]
--
gem install metanorma-cli
--

If you want the latest version (note: may not be stable due to active development),
you can install it from Github:

[source,console]
--
git clone https://github.com/riboseinc/metanorma-cli.git
cd metanorma-cli
gem build *.gemspec
gem install *.gem
bundle update
--

[TIP]
====
The Metanorma-ISO tool is a https://en.wikipedia.org/wiki/RubyGems[Ruby gem], and works on the command line. The https://en.wikipedia.org/wiki/Ruby_programming_language[Ruby programming language] can be installed on Windows (e.g. https://rubyinstaller.org), but is typically run on a Unix command line—including Linux and MacOS. The following instructions are for the Unix console.

Metanorma-ISO in turn builds on the https://asciidoctor.org[Asciidoctor gem], which interprets the Asciidoctor markup language in Ruby. Installing the Metanorma-ISO gem will install the Asciidoctor gem, if it is not already installed.

Ruby comes with Linux and MacOS. Metanorma-ISO uses Ruby 2.4.0, and you may need to update your Ruby instance to use that version. Refer to https://www.ruby-lang.org/en/documentation/installation/
====

== Setting up a new project

At its simplest, all you need is a text document in Asciidoctor-like AsciiISO format,
which you compile using the Metanorma-ISO gem.

To keep document dependencies in order, place your document in a distinct folder:

[source,console]
--
mkdir new_standard
cd new_standard
vi new_standard.adoc
--

To compile the document, execute the `asciidoctor` script, flagging it to use a specific standards class with the `-t` flag (refer to <<stupported-standards>> for the abbreviations used); e.g.

[source,console]
--
metanorma -t iso new_standard.adoc
--

This will generate two files from the `new_standard.adoc` document (provided it is well-formed):

* `new_standard.html`, a standalone HTML document,
* `new_standard.doc`, a Word document
  (currently in the pre-2007 `.doc` format, but Microsoft Word will open it fine).

Both these files are generated via an intermediate XML file,
`new_standard.xml`, which represents the structure of the document
following the rules of ISO/IEC DIR 2 (as captured in the
https://github.com/riboseinc/isodoc-models[ISOXML schema]).

Even if there are no errors in the syntax, the document may still raise warnings
to the console as it is being validated.
The validation comes from ISO/IEC DIR 2, and consists of two parts:

* Warnings about document content
  (e.g., requiring space before a percentage sign,
  or requiring that the scope not contain text that looks like a recommendation).
* Warnings about document structure
  (found from running the generated XML against the ISOXML schema,
  they report the line numbers of the XML document where issues are observed).

== Starting with an example project

Perhaps the simplest way to get started is to take an existing Metanorma-ISO document
and edit it, observing how it approaches various formatting tasks.

The https://www.iso.org/publication/PUB100407.html["Rice document"]
is the ISO's model document of an international standard.
An Metanorma-ISO version of the document is available
at https://github.com/riboseinc/isodoc-rice/.
We suggest downloading the site, and editing it.

The `iso-rice-en.adoc` document consists of a document header, and it references the separate `body/body-en.adoc` document for the document proper (`include::body/body-en.adoc[]`). You can just continue on with the document text after the document header—so long as you remember to leave a blank line between the two.

== Learning the AsciiDoc-based syntax

To author AsciiDoc documents, you need to be familiar with the _core AsciiDoc syntax_,
as well as _the syntax extensions and conventions_ that are specific to Metanorma-ISO.

- Check out link:asciiiso-syntax[our AsciiISO syntax reference],
  and link:guidance.adoc[Guidance for Authoring in Metanorma-ISO].

- See also https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
  documenting Asciidoctor itself
  and https://github.com/riboseinc/metanorma-iso/blob/master/README.adoc[Metanorma-ISO README].

== Migrating existing documents from Microsoft Word

. Use our https://github.com/riboseinc/reverse_asciidoctor[reverse_asciidoctor]
gem to help you convert a Word document into AsciiISO.
+
You will likely have to manually clean up some syntax
(especially if your Word document contains an index, stray anchors, and equations):
don’t rely on the automatic conversion to be 100% correct.

. Move the content back to the cloned isodoc-rice.


[[other-supported-standards]]
== Other supported standards 

As of this writing, Metanorma supports the following standards classes:

* https://github.com/riboseinc/metanorma-iso[ISO and IEC] (`iso`)
* https://github.com/riboseinc/metanorma-gb[Chinese National standards] (`gb`)
* https://github.com/riboseinc/metanorma-csd[Calconnect] (`csd`)
* https://github.com/riboseinc/metanorma-csand[Cloud Security Alliance] (`csand`)
* https://github.com/riboseinc/metanorma-m3d[Messaging, Malware and Mobile Anti-Abuse Working Group (M^3^AAWG)] (`m3d`)
* https://github.com/riboseinc/metanorma-rsd[Ribose] (`rsd`)
* https://github.com/riboseinc/metanorma-acme[Acme (shell for user-customised standards)] (`acme`)
* https://github.com/riboseinc/metanorma-mpfd[Mandatory Provident Fund Schemes Authority, Hong Kong (MPFA)] (`mpfd`)
* https://github.com/riboseinc/metanorma-unece[United Nations Economic Commission for Europe] (`unece`)
