= Quickstart Guide for AsciiISO

This is a guide on how to get started using AsciiISO to create ISO standards documents compliant with http://www.iec.ch/members_experts/refdocs/iec/isoiecdir-2%7Bed7.0%7Den.pdf[ISO/IEC DIR 2 "Principles and rules for the structure and drafting of ISO and IEC documents"], in Microsoft Word and HTML formats.

AsciiISO is the purposed-design syntax for creating ISO documents based on the AsciiDoc syntax.

AsciiISO is currently used as input to the Asciidoctor-ISO renderer, which produces the corresponding https://github.com/riboseinc/isodoc-models[ISOXML schema] (in `.xml`), which in turn uses the https://github.com/riboseinc/isodoc[isodoc] gem to convert ISOXML into the final output formats, HTML (`.html`) and Word Document (`.doc`).



[[installation]]
== Installing on Linux and macOS

Install Asciidoctor-ISO gem and its dependencies:

[source,console]
--
gem install metanorma-iso
--

If you want the latest version (note: may not be stable due to active development),
you can install it from Github:

[source,console]
--
git clone https://github.com/riboseinc/metanorma-iso.git
cd metanorma-iso
gem build *.gemspec
gem install *.gem
--

[TIP]
====
The Asciidoctor-ISO tool is a https://en.wikipedia.org/wiki/RubyGems[Ruby gem], and works on the command line. The https://en.wikipedia.org/wiki/Ruby_programming_language[Ruby programming language] can be installed on Windows (e.g. https://rubyinstaller.org), but is typically run on a Unix command line—including Linux and MacOS. The following instructions are for the Unix console.

Asciidoctor-ISO in turn builds on the https://asciidoctor.org[Asciidoctor gem], which interprets the Asciidoctor markup language in Ruby. Installing the Asciidoctor-ISO gem will install the Asciidoctor gem, if it is not already installed.

Ruby comes with Linux and MacOS. Asciidoctor-ISO uses Ruby 2.4.0, and you may need to update your Ruby instance to use that version. Refer to https://www.ruby-lang.org/en/documentation/installation/
====

== Setting up a new project

At its simplest, all you need is a text document in Asciidoctor format,
which you compile using the Asciidoctor-ISO gem.

To keep document dependencies in order, place your document in a distinct folder:

[source,console]
--
mkdir new_standard
cd new_standard
vi new_standard.adoc
--

To compile the document, execute the `asciidoctor` script, flagging it to use the ISO variant:

[source,console]
--
asciidoctor --trace -b iso -r 'metanorma-iso' new_standard.adoc
--

NOTE: This command syntax may change in future.

This will generate two files from the `new_standard.adoc` document (provided it is well-formed):

* `new_standard.html`, a standalone HTML document,
* `new_standard.doc`, a Word document
  (currently in the pre-2007 `.doc` format, but Microsoft Word will open it fine).

Both these files are generated via an intermediate XML file,
`new_standard.xml`, which represents the structure of the document
following the rules of ISO/IEC DIR 2 (as captured in the
https://github.com/riboseinc/isodoc-models[ISOXML schema]).

Even if there are no errors in the Asciidoctor syntax, the document may still raise warnings
to the console as it is being validated.
The validation comes from ISO/IEC DIR 2, and consists of two parts:

* Warnings about document content
  (e.g., requiring space before a percentage sign,
  or requiring that the scope not contain text that looks like a recommendation).
* Warnings about document structure
  (found from running the generated XML against the ISOXML schema,
  they report the line numbers of the XML document where issues are observed).

== Starting with an example project

Perhaps the simplest way to get started is to take an existing Asciidoctor-ISO document
and edit it, observing how it approaches various formatting tasks.

The https://www.iso.org/publication/PUB100407.html["Rice document"]
is the ISO's model document of an international standard.
An Asciidoctor-ISO version of the document is available
at https://github.com/riboseinc/isodoc-rice/.
We suggest downloading the site, and editing it.

The `iso-rice-en.adoc` document consists of a document header, and it references the separate `body/body-en.adoc` document for the document proper (`include::body/body-en.adoc[]`). You can just continue on with the document text after the document header—so long as you remember to leave a blank line between the two.

== Learning the AsciiDoc-based syntax

To author AsciiDoc documents, you need to be familiar with the <em>core AsciiDoc syntax</em>,
as well as <em>the syntax extensions and conventions</em> that are specific to Metanorma-ISO.

- Check out link:asciiiso-syntax[our AsciiISO syntax reference],
  and link:guidance.adoc[Guidance for Authoring in Asciidoctor-ISO].

- See also https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
  documenting Asciidoctor itself
  and https://github.com/riboseinc/metanorma-iso/blob/master/README.adoc[Metanorma-ISO README].

== Migrating existing documents from Microsoft Word:

. Use our https://github.com/riboseinc/reverse_asciidoctor[reverse_asciidoctor]
  gem to help you convert a Word document into AsciiISO.
+
You will likely have to manually clean up some syntax
(especially if your Word document contains an index, stray anchors, and equations):
don’t rely on the automatic conversion to be 100% correct.

. Move the content back to the cloned isodoc-rice.
