name: rake

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:

jobs:
  rake:
    uses: metanorma/ci/.github/workflows/mn-processor-rake.yml@feature/run-templates-samples-test-on-processors-ci
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
